name: mindful_flutter_auth
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.3.1

dependencies:
  flutter_animate: ^4.5.0
  flutter_secure_storage: ^9.0.0
  go_router: ^14.0.1
  mindful_flutter_util:
      path: ../mindful_flutter_util
  quiver: ^3.2.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  supabase_auth_ui: ^0.4.4
  sign_in_button: ^3.2.0
  supabase_flutter: ^2.5.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  lints: ^3.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  test: ^1.24.0

dependency_overrides:
  intl: 0.19.0