name: mindful_flutter_auth
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.3.1

dependencies:
  flutter_login: ^5.0.0
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.2
  mindful_flutter_util:
      path: ../mindful_flutter_util
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  supabase: ^2.0.9
  supabase_flutter: ^2.4.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  lints: ^3.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  test: ^1.24.0
