name: mindful_flutter_auth
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.3.1

dependencies:
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_ui_auth: ^1.15.0
  firebase_ui_firestore: ^1.6.4
  firebase_ui_oauth: ^1.5.3
  firebase_ui_oauth_google: ^1.3.3
  get_it: ^7.7.0
  go_router: ^14.2.7
#  mindful_dart_util: ^0.9.0
  mindful_dart_util:
    path: ../mindful_dart_util
  mindful_flutter_util:
      path: ../mindful_flutter_util
  quiver: ^3.2.1
  riverpod_annotation: ^2.3.5
  supabase_auth_ui: ^0.5.1
  sign_in_button: ^3.2.0
  supabase_flutter: ^2.6.0
  # path: ^1.8.0
  watch_it: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.4
  lints: ^4.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  test: ^1.24.0

dependency_overrides:
  intl: 0.19.0
