name: mindful_flutter_auth
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.3.1

dependencies:
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.3
  flutter_secure_storage: ^9.2.2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_ui_auth: ^1.16.0
  firebase_ui_firestore: ^1.7.0
  firebase_ui_oauth: ^1.6.0
  firebase_ui_oauth_google: ^1.4.0
  get_it: ^8.0.0
  go_router: ^14.3.0
#  mindful_dart_util: ^0.9.0
  mindful_dart_util:
    path: ../mindful_dart_util
  mindful_flutter_util:
      path: ../mindful_flutter_util
  quiver: ^3.2.2
  riverpod_annotation: ^2.5.3
  supabase_auth_ui: ^0.5.3
  sign_in_button: ^3.2.0
  supabase_flutter: ^2.8.0
  # path: ^1.8.0
  watch_it: ^1.5.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.10
  lints: ^5.0.0
  riverpod_generator: ^2.4.4
  riverpod_lint: ^2.3.14
  test: ^1.24.0

dependency_overrides:
  intl: 0.19.0
